version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../gabrielvictorapi/development.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    extends:
      file: ../gabrielvictorapi/docker-compose.yaml  
      service: db 

volumes:
  postgres_data: